# WARNING : This file is machine generated by run_robot_caliblate_mode.py.
# Edit at your own risk.
import numpy as np
NEUTRAL_ANGLE_DEGREES = np.array(
[[-6.0, -0.5, -1.0, -5.5], [28.5, 34.5, 39.5, 30.0], [-49.0, -55.5, -47.5, -45.5]]
)
