# WARNING : This file is machine generated by run_robot_caliblate_mode.py.
# Edit at your own risk.
import numpy as np
NEUTRAL_ANGLE_DEGREES = np.array(
[[0.0, 0.0, 0.0, 0.0], [45.0, 45.0, 45.0, 45.0], [45.0, 45.0, 45.0, 45.0]]
)
